 # print("----------------------------Iterate using set comprehension----------------------")
        # start = timer()
        # test_set_comprehension(test_set)
        # end = timer()
        # print(str(end- start))